# Generated by Django 3.0.4 on 2020-12-19 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordslearn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordeng',
            name='word_type',
            field=models.CharField(blank=True, choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb'), ('preposition', 'Preposition'), ('Conjunctions', 'Conjunctions'), ('other', 'Other')], help_text='Select type of word', max_length=30),
        ),
        migrations.AlterField(
            model_name='wordpol',
            name='word_type',
            field=models.CharField(blank=True, choices=[('Noun', 'rzeczownik'), ('Verb', 'czasownik'), ('Adjective', 'przymiotnik'), ('Adverb', 'przyslowek'), ('Preposition', 'przyimek'), ('Conjunctions', 'spójnik'), ('Other', 'inne')], help_text='Select type of word', max_length=30),
        ),
    ]
