# Generated by Django 3.0.4 on 2020-05-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordslearn', '0002_auto_20200512_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordeng',
            name='date_of_add',
            field=models.DateTimeField(auto_now=True, help_text='date added'),
        ),
        migrations.AddField(
            model_name='wordpol',
            name='date_of_add',
            field=models.DateTimeField(auto_now=True, help_text='date added'),
        ),
    ]
